version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: 'db'
    restart: on-failure
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - backend
    volumes:
      - db-store:/var/lib/mysql

  buggregator:
    container_name: buggregator
    image: ghcr.io/buggregator/server:dev
    ports:
      - "8001:8000"
      - "1025:1025"
      - "9912:9912"
      - "9913:9913"
    networks:
      - backend


networks:
  backend:
    name: backend
    driver: bridge

volumes:
  db-store:
